import type { RoadmapStage, RoadmapStageKey } from '../types/roadmap';

export const LABX_FUNDING_PROGRAM = {
  id: 'labx-core-funding-v1',
  name: 'LabX Core Funding',
  pointsThreshold: 25000,
  maximumFundingAmount: 'UP TO ₹1,00,000',
  currency: 'INR',
  eligibilityRules: [
    'Must reach 25,000 LABX points',
    'Must have a completed MVP',
    'Must pass LabX manual review',
  ],
  status: 'ACTIVE' as const,
};

export const DEFAULT_ROADMAP_STAGES: Omit<RoadmapStage, 'status' | 'progress' | 'completedAt' | 'milestones'>[] = [
  {
    id: 'IDEA',
    order: 1,
    name: 'IDEA',
    slug: 'idea',
    tagline: 'Turn a thought into a clearly defined opportunity.',
    description: 'Transform an initial thought into a clearly articulated problem, target audience, and proposed solution.',
    objective: 'Transform an initial thought into a clearly articulated problem, target audience, and proposed solution.',
    activities: ['Define the problem', 'Identify target users', 'Understand why the problem matters', 'Define the proposed solution', 'Describe expected value', 'Create the initial project concept'],
    deliverables: ['Problem statement', 'Target user profile', 'Solution statement', 'Value proposition', 'Initial project brief'],
    completionCriteria: 'The user can clearly explain: WHAT problem am I solving? WHO am I solving it for? WHAT am I proposing? WHY does it matter?',
    requiredPoints: 0,
    rewardPoints: 500,
  },
  {
    id: 'VALIDATE',
    order: 2,
    name: 'VALIDATE',
    slug: 'validate',
    tagline: 'Turn assumptions into evidence.',
    description: 'Determine whether the identified problem exists and whether the proposed solution has meaningful potential.',
    objective: 'Determine whether the identified problem exists and whether the proposed solution has meaningful potential.',
    activities: ['Market research', 'Competitor analysis', 'User interviews', 'User surveys', 'Problem validation', 'Solution validation', 'Identify market gaps'],
    deliverables: ['Market research', 'Competitor map', 'User research', 'Validation evidence', 'Market opportunity summary'],
    completionCriteria: 'Evidence supports: PROBLEM EXISTENCE + USER NEED + SOLUTION RELEVANCE',
    requiredPoints: 500,
    rewardPoints: 1000,
  },
  {
    id: 'PLAN',
    order: 3,
    name: 'PLAN',
    slug: 'plan',
    tagline: 'Give the idea a direction.',
    description: 'Convert the validated concept into a practical product, technical, and business plan.',
    objective: 'Convert the validated concept into a practical product, technical, and business plan.',
    activities: ['Define product scope', 'Prioritize features', 'Choose technology', 'Define architecture', 'Create roadmap', 'Define business model', 'Identify required skills', 'Define team requirements'],
    deliverables: ['Product specification', 'Feature list', 'Technical architecture', 'Technology stack', 'Product roadmap', 'Business model', 'Team requirements'],
    completionCriteria: 'The user knows: WHAT to build HOW to build it WHO is needed WHAT comes first',
    requiredPoints: 1500,
    rewardPoints: 1500,
  },
  {
    id: 'BUILD',
    order: 4,
    name: 'BUILD',
    slug: 'build',
    tagline: 'Turn the plan into something real.',
    description: 'Build the actual product and begin meaningful collaboration.',
    objective: 'Build the actual product and begin meaningful collaboration.',
    activities: ['Create repository', 'Set up architecture', 'Build core features', 'Develop frontend/backend', 'Build team', 'Collaborate', 'Track contributions', 'Publish progress'],
    deliverables: ['Working code', 'Repository', 'Product components', 'Technical documentation', 'Team contributions', 'Build updates'],
    completionCriteria: 'The product has meaningful working functionality.',
    requiredPoints: 3000,
    rewardPoints: 2500,
  },
  {
    id: 'MVP',
    order: 5,
    name: 'MVP',
    slug: 'mvp',
    tagline: 'Build the smallest version that creates real value.',
    description: 'Create a usable minimum viable product and test it with real users.',
    objective: 'Create a usable minimum viable product and test it with real users.',
    activities: ['Complete MVP', 'User testing', 'Collect feedback', 'Fix critical issues', 'Improve usability', 'Measure early usage', 'Iterate'],
    deliverables: ['Working MVP', 'Demo', 'User feedback', 'Bug report', 'Product metrics', 'Iteration notes'],
    completionCriteria: 'Real users can use the product and provide meaningful feedback.',
    requiredPoints: 5500,
    rewardPoints: 3500,
  },
  {
    id: 'LAUNCH',
    order: 6,
    name: 'LAUNCH',
    slug: 'launch',
    tagline: 'Take your product beyond the build.',
    description: 'Release the product publicly and acquire the first meaningful users.',
    objective: 'Release the product publicly and acquire the first meaningful users.',
    activities: ['Public launch', 'Product showcase', 'Community promotion', 'First user acquisition', 'Build-in-public updates', 'Launch feedback', 'Establish product presence'],
    deliverables: ['Live product', 'Demo URL', 'Launch announcement', 'Product showcase', 'Early traction metrics'],
    completionCriteria: 'The product is publicly available and has real-world users or measurable engagement.',
    requiredPoints: 9000,
    rewardPoints: 4000,
  },
  {
    id: 'GROW',
    order: 7,
    name: 'GROW',
    slug: 'grow',
    tagline: 'Turn early traction into momentum.',
    description: 'Increase users, engagement, revenue, partnerships, and community presence.',
    objective: 'Increase users, engagement, revenue, partnerships, and community presence.',
    activities: ['User growth', 'Product improvement', 'Community building', 'Partnerships', 'Revenue generation', 'Marketing', 'Retention improvement'],
    deliverables: ['Growth metrics', 'Revenue metrics', 'Partnership records', 'Community metrics', 'Growth experiments'],
    completionCriteria: 'The product demonstrates measurable and repeatable growth.',
    requiredPoints: 13000,
    rewardPoints: 4500,
  },
  {
    id: 'SCALE',
    order: 8,
    name: 'SCALE',
    slug: 'scale',
    tagline: 'Build systems that can handle what comes next.',
    description: 'Prepare the product, team, infrastructure, and operations for larger scale.',
    objective: 'Prepare the product, team, infrastructure, and operations for larger scale.',
    activities: ['Infrastructure scaling', 'Team expansion', 'Process development', 'Automation', 'Market expansion', 'Security improvement', 'Performance optimization', 'Operational maturity'],
    deliverables: ['Scalable infrastructure', 'Team structure', 'Operational processes', 'Performance metrics', 'Expansion plan'],
    completionCriteria: 'The product has systems capable of supporting significantly larger adoption.',
    requiredPoints: 17500,
    rewardPoints: 4000,
  },
  {
    id: 'IMPACT',
    order: 9,
    name: 'IMPACT',
    slug: 'impact',
    tagline: 'Create measurable value that lasts.',
    description: 'Demonstrate meaningful long-term impact, sustainability, and readiness for the next level.',
    objective: 'Demonstrate meaningful long-term impact, sustainability, and readiness for the next level.',
    activities: ['Measure impact', 'Track long-term growth', 'Demonstrate sustainability', 'Expand reach', 'Establish long-term strategy', 'Demonstrate traction', 'Prepare for funding or strategic growth'],
    deliverables: ['Impact report', 'Growth metrics', 'Long-term roadmap', 'Traction evidence', 'Funding readiness profile'],
    completionCriteria: 'The project demonstrates meaningful impact and sustainable progress.',
    requiredPoints: 21500,
    rewardPoints: 2000,
  },
];
