import type { RoadmapStage, RoadmapStageKey } from '../types/roadmap';

export const LABX_FUNDING_PROGRAM = {
  id: 'labx-core-funding-v1',
  name: 'LabX Core Funding',
  pointsThreshold: 25000,
  maximumFundingAmount: 'UP TO ₹1,00,000',
  currency: 'INR',
  eligibilityRules: [
    'Must reach 25,000 LABX points',
    'Must have a completed MVP',
    'Must pass LabX manual review',
  ],
  status: 'ACTIVE' as const,
};

export const DEFAULT_ROADMAP_STAGES: Omit<RoadmapStage, 'status' | 'progress' | 'completedAt' | 'milestones'>[] = [
  {
    id: 'IDEA',
    order: 1,
    name: 'IDEA',
    slug: 'idea',
    description: 'Turn an initial idea into a clearly defined problem and solution.',
    goals: [
      'Define the problem',
      'Identify target users',
      'Define the proposed solution',
      'Explain why the problem matters',
    ],
    requiredPoints: 0,
    rewardPoints: 500,
  },
  {
    id: 'VALIDATE',
    order: 2,
    name: 'VALIDATE',
    slug: 'validate',
    description: 'Determine whether the problem and proposed solution have real-world relevance.',
    goals: [
      'Market research',
      'Competitor research',
      'User interviews',
      'Problem validation',
      'Solution validation',
    ],
    requiredPoints: 500,
    rewardPoints: 1000,
  },
  {
    id: 'PLAN',
    order: 3,
    name: 'PLAN',
    slug: 'plan',
    description: 'Turn the validated idea into a structured product plan.',
    goals: [
      'Product scope',
      'Feature planning',
      'Technology selection',
      'Business model',
      'Team planning',
      'Product roadmap',
    ],
    requiredPoints: 1500,
    rewardPoints: 1500,
  },
  {
    id: 'BUILD',
    order: 4,
    name: 'BUILD',
    slug: 'build',
    description: 'Turn the plan into a working product.',
    goals: [
      'Create repository',
      'Build core features',
      'Develop product',
      'Build team',
      'Track contributions',
    ],
    requiredPoints: 3000,
    rewardPoints: 2500,
  },
  {
    id: 'MVP',
    order: 5,
    name: 'MVP',
    slug: 'mvp',
    description: 'Create a usable minimum viable product and test it with real users.',
    goals: [
      'Working MVP',
      'User testing',
      'Feedback',
      'Bug fixing',
      'Product iteration',
    ],
    requiredPoints: 5500,
    rewardPoints: 3500,
  },
  {
    id: 'LAUNCH',
    order: 6,
    name: 'LAUNCH',
    slug: 'launch',
    description: 'Release the product publicly.',
    goals: [
      'Public launch',
      'First users',
      'Visibility',
      'Product showcase',
      'Community awareness',
    ],
    requiredPoints: 9000,
    rewardPoints: 4000,
  },
  {
    id: 'GROW',
    order: 7,
    name: 'GROW',
    slug: 'grow',
    description: 'Increase adoption and build sustainable traction.',
    goals: [
      'Increase users',
      'Improve engagement',
      'Revenue',
      'Partnerships',
      'Community growth',
    ],
    requiredPoints: 13000,
    rewardPoints: 4500,
  },
  {
    id: 'SCALE',
    order: 8,
    name: 'SCALE',
    slug: 'scale',
    description: 'Prepare the product/startup for larger adoption.',
    goals: [
      'Infrastructure',
      'Team expansion',
      'Operations',
      'Market expansion',
      'Process improvement',
    ],
    requiredPoints: 17500,
    rewardPoints: 4000,
  },
  {
    id: 'IMPACT',
    order: 9,
    name: 'IMPACT',
    slug: 'impact',
    description: 'Demonstrate meaningful long-term impact and maturity.',
    goals: [
      'Impact metrics',
      'Sustainable growth',
      'Strong traction',
      'Long-term roadmap',
      'Funding readiness',
    ],
    requiredPoints: 21500,
    rewardPoints: 2000,
  }
];
